### ISSUE TITLE
This package is looking for a maintainer

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge-archlinux#10]
@maxpoulin64 is currently maintaining this, but we would like a second maintainer to help.

Mainly, when a new version of The Lounge is released, make sure the correct pieces pushed to the correct places. @maxpoulin64, mind giving some details of what you do when a release happens? Not sure what the steps are.

**Comment by brunnre8** [comment]
I'd be happy to help.
I anyhow run thelounge on an Arch server, so it's kinda self interest to see the aur package maintained :stuck_out_tongue:

**Comment by maxpoulin64** [comment]
@brunnre8 You seem to know what you're doing and your updated PR for 3.0.0 was super helpful, and we definitely want someone that runs the package to maintain it. I'm quite happy you took the time to clean it up and make use of systemd's new protection features and all. I would feel comfortable adding you as a maintainer. Not sure how the others want to proceed with this, I can give you maintainer access or we can go with PRs for now for validation.

@astorije Literally `git push aur`, where `aur` is the AUR git server :stuck_out_tongue: The AUR web interface looks for the data in the `.SRCINFO` file so as long as this file is updated properly along with the `PKGBUILD`, that's pretty much it. `.SRCINFO` itself is generated by `makepkg --printsrcinfo`. So it's really nothing more than committing the latest version to master and pushing, wait a few seconds, and it's live.

**Comment by astorije** [comment]
I'm fine with anything you and @xPaw prefer. We do need a maintainer, and @brunnre8 you seem motivated enough :) Thanks for offering your help! 🙏

**Comment by brunnre8** [comment]
@maxpoulin64 I've been granted push access to the repo by xPaw.

Could you please add this account as a co-maintainer on the aur: https://aur.archlinux.org/account/S13ntist?
You can do this directly on the aur page ("manage co-maintainers")

Then we should be all set.

**Comment by maxpoulin64** [comment]
@brunnre8 Done!

**Comment by brunnre8** [comment]
great, thanks :smiley:
