### ISSUE TITLE
yarn test in check function

### ISSUE THREAD

**Issue by aminvakil** [thelounge/thelounge-archlinux#21]
It's good (?) to add `check` function and run `yarn test` inside it.

I maintain https://aur.archlinux.org/packages/thelounge-beta and tried adding it without luck in https://github.com/aminvakil/aur/pull/125 (https://github.com/aminvakil/aur/runs/5988936609?check_suite_focus=true).

**Comment by brunnre8** [comment]
Don't see the need here. The software is tested in our upstream repo, The only tests that would be interesting are those related to the packaging itself.

**Comment by aminvakil** [comment]
https://man.archlinux.org/man/PKGBUILD.5#PACKAGING_FUNCTIONS:

> check() Function
An optional check() function can be specified in which a package’s test-suite may be run. This function is run between the build() and package() functions. Be sure any exotic commands used are covered by the checkdepends array.

AFAICS it should be related to built application as it executes before `package()` function, but if you don't see the need here, we can leave it be.

**Comment by brunnre8** [comment]
well, sure but it's JavaScript.
We aren't compiling anything in the normal case.
The only thing that you are compiling *might* be sqlite3 and only if it can't find a binary blob.
Missing sqlite3 is not a fatal error as it's an optional dep as far as upstream is concerned
