### ISSUE TITLE
File `thelounge.stamp` causes issue "passing the validity check"

### ISSUE THREAD

**Issue by Techcable** [thelounge/thelounge-archlinux#22]
Cloning a fresh copy of the AUR package and running `makepkg`, I encounter the following error message:

```
==> Validating source files with sha256sums...
    thelounge-4.4.1.tgz ... Passed
    yarn.lock ... FAILED
    package.json ... FAILED
    system.service ... Passed
    user.service ... Passed
    sysusers.d ... Passed
    tmpfiles.d ... Passed
==> ERROR: One or more files did not pass the validity check!
FAILED: thelounge.stamp 
```

Here is a link to the full logs: https://gist.github.com/Techcable/b6269c595dabbe1459eacbdaff9119d4

**Comment by Techcable** [comment]
Looks like running `updpkgsums` fixes it.

**Comment by brunnre8** [comment]
yeah, sorry for that.
I did run updpgksums but it's stupid and doesn't re-fetch the sources and took the bad one I already had in the local dir.

Don't run build in a dirty tree kids.

Should be fixed
